[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "http://www.omdbapi.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
